export const TOAST_BOTTOM_OFFSET = 20;

export const CUSTOM_POPUP_MIN_HEIGHT = 150;

export const FLAT_LIST_FOOTER_HEIGHT = 200;
export const FLAT_LIST_FOOTER_LOADER_HEIGHT = 100;

export const CUSTOM_HEADER_HEIGHT = 56;

export const HITSLOP_DIMENSION = 10;

export const SEARCH_ICONS_DIMENTION = 20;

export const SEARCH_BAR_HORIZONTAL_PADDING = 16;

export const HeightDimentions = {
  HEIGHT_DIVIDER_1: 5,
  HEIGHT_DIVIDER_2: 10,
  HEIGHT_DIVIDER_3: 20,
  HEIGHT_DIVIDER_4: 30,
  HEIGHT_DIVIDER_5: 50,
  HEIGHT_FLATLIST_SEPARATOR: 15,
};

export const WidthDimentions = {
  WIDTH_DIVIDER_1: 5,
  WIDTH_DIVIDER_2: 10,
  WIDTH_DIVIDER_3: 20,
  WIDTH_DIVIDER_4: 30,
  WIDTH_REACTION_DIVIDER: 2,
};

export const LineHeights = {
  LINE_HEIGHT_1: 19.6,
  LINE_HEIGHT_2: 21.6,
  LINE_HEIGHT_3: 27.6,
};

export const POST_LIST_IMAGE_DIMENSION = 200;
export const POST_DETAILS_IMAGE_DIMENSION = 400;
